on:
    push:
      branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go
        run: scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
 
      - name: 'gcloud builds submit'
        run: 'gcloud builds submit --tag europe-west10-docker.pkg.dev/notely-431717/notely-ar-repo/notely-app:v1'

      - name: 'Set up Goose'
        run: 'go install github.com/pressly/goose/v3/cmd/goose@latest'

      - name: 'chmod migration script'
        run: 'chmod u+x ./scripts/migrateup.sh'

      - name: 'Migrate DB'
        run: './scripts/migrateup.sh'

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west10-docker.pkg.dev/notely-431717/notely-ar-repo/notely-app:v1 --region europe-west1 --allow-unauthenticated --project notely-431717 --max-instances=4